# Generated by Django 3.1.6 on 2021-02-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
